[window]
startup_mode = "Maximized"
opacity = 0.9
option_as_alt = "OnlyLeft"

# [terminal]
# shell = { program = "wsl", args = ["--cd", "~"] }

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
size = 12.0
